[2023-07-25 20:38:12,394] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T09:20:00+00:00 [queued]>
[2023-07-25 20:38:12,414] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T09:20:00+00:00 [queued]>
[2023-07-25 20:38:12,415] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-25 20:38:12,416] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-25 20:38:12,416] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-25 20:38:12,451] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): fetch_exchange_rates_task> on 2023-07-25 09:20:00+00:00
[2023-07-25 20:38:12,457] {standard_task_runner.py:52} INFO - Started process 9136 to run task
[2023-07-25 20:38:12,476] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fetch_exchange_rates_dag', 'fetch_exchange_rates_task', 'scheduled__2023-07-25T09:20:00+00:00', '--job-id', '154', '--raw', '--subdir', 'DAGS_FOLDER/my_calc_rates.py', '--cfg-path', '/tmp/tmp98e6h5lw', '--error-file', '/tmp/tmpl_gki68b']
[2023-07-25 20:38:12,478] {standard_task_runner.py:80} INFO - Job 154: Subtask fetch_exchange_rates_task
[2023-07-25 20:38:12,626] {task_command.py:371} INFO - Running <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T09:20:00+00:00 [running]> on host 661c8d62a693
[2023-07-25 20:38:12,796] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=marina_z
AIRFLOW_CTX_DAG_ID=fetch_exchange_rates_dag
AIRFLOW_CTX_TASK_ID=fetch_exchange_rates_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-25T09:20:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-25T09:20:00+00:00
[2023-07-25 20:38:14,470] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_calc_rates.py", line 69, in fetch_exchange_rates
    load_to_postgres = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2023-07-25 20:38:14,503] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=fetch_exchange_rates_dag, task_id=fetch_exchange_rates_task, execution_date=20230725T092000, start_date=20230725T203812, end_date=20230725T203814
[2023-07-25 20:38:14,604] {standard_task_runner.py:97} ERROR - Failed to execute job 154 for task fetch_exchange_rates_task (name 'PostgresOperator' is not defined; 9136)
[2023-07-25 20:38:14,631] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-25 20:38:14,708] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-26 05:04:47,643] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T09:20:00+00:00 [queued]>
[2023-07-26 05:04:47,660] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T09:20:00+00:00 [queued]>
[2023-07-26 05:04:47,662] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 05:04:47,663] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-26 05:04:47,664] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 05:04:47,699] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): fetch_exchange_rates_task> on 2023-07-25 09:20:00+00:00
[2023-07-26 05:04:47,706] {standard_task_runner.py:52} INFO - Started process 861 to run task
[2023-07-26 05:04:47,712] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fetch_exchange_rates_dag', 'fetch_exchange_rates_task', 'scheduled__2023-07-25T09:20:00+00:00', '--job-id', '201', '--raw', '--subdir', 'DAGS_FOLDER/my_calc_rates.py', '--cfg-path', '/tmp/tmppg4ird13', '--error-file', '/tmp/tmp7amos7w2']
[2023-07-26 05:04:47,715] {standard_task_runner.py:80} INFO - Job 201: Subtask fetch_exchange_rates_task
[2023-07-26 05:04:47,848] {task_command.py:371} INFO - Running <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T09:20:00+00:00 [running]> on host acb6bca32630
[2023-07-26 05:04:47,994] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=marina_z
AIRFLOW_CTX_DAG_ID=fetch_exchange_rates_dag
AIRFLOW_CTX_TASK_ID=fetch_exchange_rates_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-25T09:20:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-25T09:20:00+00:00
[2023-07-26 05:04:48,370] {logging_mixin.py:115} INFO - Save a new file exchange_latest_BTC.csv
[2023-07-26 05:04:48,372] {logging_mixin.py:115} INFO - Create a new table exchange_latest_BTC
[2023-07-26 05:04:48,379] {logging_mixin.py:115} INFO - Insert into table exchange_latest_BTC
[2023-07-26 05:04:48,393] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_calc_rates.py", line 99, in fetch_exchange_rates
    cur.execute(copy_query)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type numeric: "2023-07-26"
CONTEXT:  COPY exchange_rates_btc, line 3, column exchange_rate: "2023-07-26"

[2023-07-26 05:04:48,406] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=fetch_exchange_rates_dag, task_id=fetch_exchange_rates_task, execution_date=20230725T092000, start_date=20230726T050447, end_date=20230726T050448
[2023-07-26 05:04:48,420] {standard_task_runner.py:97} ERROR - Failed to execute job 201 for task fetch_exchange_rates_task (invalid input syntax for type numeric: "2023-07-26"
CONTEXT:  COPY exchange_rates_btc, line 3, column exchange_rate: "2023-07-26"
; 861)
[2023-07-26 05:04:48,446] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-26 05:04:48,492] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
