[2023-07-25 20:38:39,325] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T16:00:00+00:00 [queued]>
[2023-07-25 20:38:39,395] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T16:00:00+00:00 [queued]>
[2023-07-25 20:38:39,396] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-25 20:38:39,397] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-25 20:38:39,397] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-25 20:38:39,453] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): fetch_exchange_rates_task> on 2023-07-25 16:00:00+00:00
[2023-07-25 20:38:39,471] {standard_task_runner.py:52} INFO - Started process 9275 to run task
[2023-07-25 20:38:39,485] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fetch_exchange_rates_dag', 'fetch_exchange_rates_task', 'scheduled__2023-07-25T16:00:00+00:00', '--job-id', '194', '--raw', '--subdir', 'DAGS_FOLDER/my_calc_rates.py', '--cfg-path', '/tmp/tmp5bmozqp3', '--error-file', '/tmp/tmpskq33pg0']
[2023-07-25 20:38:39,517] {standard_task_runner.py:80} INFO - Job 194: Subtask fetch_exchange_rates_task
[2023-07-25 20:38:39,734] {task_command.py:371} INFO - Running <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T16:00:00+00:00 [running]> on host 661c8d62a693
[2023-07-25 20:38:39,979] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=marina_z
AIRFLOW_CTX_DAG_ID=fetch_exchange_rates_dag
AIRFLOW_CTX_TASK_ID=fetch_exchange_rates_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-25T16:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-25T16:00:00+00:00
[2023-07-25 20:38:41,887] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_calc_rates.py", line 69, in fetch_exchange_rates
    load_to_postgres = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2023-07-25 20:38:41,910] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=fetch_exchange_rates_dag, task_id=fetch_exchange_rates_task, execution_date=20230725T160000, start_date=20230725T203839, end_date=20230725T203841
[2023-07-25 20:38:41,945] {standard_task_runner.py:97} ERROR - Failed to execute job 194 for task fetch_exchange_rates_task (name 'PostgresOperator' is not defined; 9275)
[2023-07-25 20:38:42,022] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-25 20:38:42,099] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-26 05:05:57,554] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T16:00:00+00:00 [queued]>
[2023-07-26 05:05:57,601] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T16:00:00+00:00 [queued]>
[2023-07-26 05:05:57,610] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 05:05:57,610] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-26 05:05:57,611] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 05:05:57,756] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): fetch_exchange_rates_task> on 2023-07-25 16:00:00+00:00
[2023-07-26 05:05:57,821] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fetch_exchange_rates_dag', 'fetch_exchange_rates_task', 'scheduled__2023-07-25T16:00:00+00:00', '--job-id', '338', '--raw', '--subdir', 'DAGS_FOLDER/my_calc_rates.py', '--cfg-path', '/tmp/tmppbionmiv', '--error-file', '/tmp/tmphi8gmjgs']
[2023-07-26 05:05:57,827] {standard_task_runner.py:80} INFO - Job 338: Subtask fetch_exchange_rates_task
[2023-07-26 05:05:57,841] {standard_task_runner.py:52} INFO - Started process 1376 to run task
[2023-07-26 05:05:58,525] {task_command.py:371} INFO - Running <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T16:00:00+00:00 [running]> on host acb6bca32630
[2023-07-26 05:05:59,201] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=marina_z
AIRFLOW_CTX_DAG_ID=fetch_exchange_rates_dag
AIRFLOW_CTX_TASK_ID=fetch_exchange_rates_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-25T16:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-25T16:00:00+00:00
[2023-07-26 05:05:59,718] {logging_mixin.py:115} INFO - Save a new file exchange_latest_BTC.csv
[2023-07-26 05:05:59,719] {logging_mixin.py:115} INFO - Create a new table exchange_latest_BTC
[2023-07-26 05:05:59,726] {logging_mixin.py:115} INFO - Insert into table exchange_latest_BTC
[2023-07-26 05:06:00,164] {logging_mixin.py:115} INFO - Save a new file exchange_latest_EUR.csv
[2023-07-26 05:06:00,168] {logging_mixin.py:115} INFO - Create a new table exchange_latest_EUR
[2023-07-26 05:06:00,219] {logging_mixin.py:115} INFO - Insert into table exchange_latest_EUR
[2023-07-26 05:06:00,587] {logging_mixin.py:115} INFO - Save a new file exchange_latest_GBR.csv
[2023-07-26 05:06:00,590] {logging_mixin.py:115} INFO - Create a new table exchange_latest_GBR
[2023-07-26 05:06:00,597] {logging_mixin.py:115} INFO - Insert into table exchange_latest_GBR
[2023-07-26 05:06:00,623] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_calc_rates.py", line 99, in fetch_exchange_rates
    cur.execute(copy_query)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type numeric: "2023-07-26"
CONTEXT:  COPY exchange_rates_gbr, line 3, column exchange_rate: "2023-07-26"

[2023-07-26 05:06:00,653] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=fetch_exchange_rates_dag, task_id=fetch_exchange_rates_task, execution_date=20230725T160000, start_date=20230726T050557, end_date=20230726T050600
[2023-07-26 05:06:00,799] {standard_task_runner.py:97} ERROR - Failed to execute job 338 for task fetch_exchange_rates_task (invalid input syntax for type numeric: "2023-07-26"
CONTEXT:  COPY exchange_rates_gbr, line 3, column exchange_rate: "2023-07-26"
; 1376)
[2023-07-26 05:06:00,879] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-26 05:06:01,093] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
