[2023-07-26 23:53:55,021] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T02:20:00+00:00 [queued]>
[2023-07-26 23:53:55,066] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T02:20:00+00:00 [queued]>
[2023-07-26 23:53:55,069] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 23:53:55,070] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-26 23:53:55,071] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 23:53:55,169] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): fetch_exchange_rates_task> on 2023-07-25 02:20:00+00:00
[2023-07-26 23:53:55,204] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fetch_exchange_rates_dag', 'fetch_exchange_rates_task', 'scheduled__2023-07-25T02:20:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/my_calc_rates.py', '--cfg-path', '/tmp/tmpkidtcjf8', '--error-file', '/tmp/tmp6haeq536']
[2023-07-26 23:53:55,207] {standard_task_runner.py:80} INFO - Job 30: Subtask fetch_exchange_rates_task
[2023-07-26 23:53:55,205] {standard_task_runner.py:52} INFO - Started process 370 to run task
[2023-07-26 23:53:55,412] {task_command.py:371} INFO - Running <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T02:20:00+00:00 [running]> on host 43d0198bb36a
[2023-07-26 23:53:55,692] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=marina_z
AIRFLOW_CTX_DAG_ID=fetch_exchange_rates_dag
AIRFLOW_CTX_TASK_ID=fetch_exchange_rates_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-25T02:20:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-25T02:20:00+00:00
[2023-07-26 23:53:56,110] {logging_mixin.py:115} INFO - Save a new file exchange_latest_BTC.csv
[2023-07-26 23:53:56,116] {logging_mixin.py:115} INFO - Create a new table exchange_latest_BTC
[2023-07-26 23:53:56,129] {logging_mixin.py:115} INFO - Insert into table exchange_latest_BTC
[2023-07-26 23:53:56,150] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_calc_rates.py", line 99, in fetch_exchange_rates
    cur.execute(copy_query)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type numeric: "2625679,657895"
CONTEXT:  COPY exchange_rates_btc, line 2, column exchange_rate: "2625679,657895"

[2023-07-26 23:53:56,184] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=fetch_exchange_rates_dag, task_id=fetch_exchange_rates_task, execution_date=20230725T022000, start_date=20230726T235355, end_date=20230726T235356
[2023-07-26 23:53:56,231] {standard_task_runner.py:97} ERROR - Failed to execute job 30 for task fetch_exchange_rates_task (invalid input syntax for type numeric: "2625679,657895"
CONTEXT:  COPY exchange_rates_btc, line 2, column exchange_rate: "2625679,657895"
; 370)
[2023-07-26 23:53:56,294] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-26 23:53:56,383] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
