[2023-07-25 20:38:38,843] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T15:50:00+00:00 [queued]>
[2023-07-25 20:38:38,868] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T15:50:00+00:00 [queued]>
[2023-07-25 20:38:38,869] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-25 20:38:38,870] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-25 20:38:38,870] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-25 20:38:38,918] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): fetch_exchange_rates_task> on 2023-07-25 15:50:00+00:00
[2023-07-25 20:38:38,931] {standard_task_runner.py:52} INFO - Started process 9272 to run task
[2023-07-25 20:38:38,935] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fetch_exchange_rates_dag', 'fetch_exchange_rates_task', 'scheduled__2023-07-25T15:50:00+00:00', '--job-id', '193', '--raw', '--subdir', 'DAGS_FOLDER/my_calc_rates.py', '--cfg-path', '/tmp/tmpmrpo_v_h', '--error-file', '/tmp/tmpazgbmzjo']
[2023-07-25 20:38:38,939] {standard_task_runner.py:80} INFO - Job 193: Subtask fetch_exchange_rates_task
[2023-07-25 20:38:39,186] {task_command.py:371} INFO - Running <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T15:50:00+00:00 [running]> on host 661c8d62a693
[2023-07-25 20:38:39,415] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=marina_z
AIRFLOW_CTX_DAG_ID=fetch_exchange_rates_dag
AIRFLOW_CTX_TASK_ID=fetch_exchange_rates_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-25T15:50:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-25T15:50:00+00:00
[2023-07-25 20:38:41,288] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_calc_rates.py", line 69, in fetch_exchange_rates
    load_to_postgres = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2023-07-25 20:38:41,322] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=fetch_exchange_rates_dag, task_id=fetch_exchange_rates_task, execution_date=20230725T155000, start_date=20230725T203838, end_date=20230725T203841
[2023-07-25 20:38:41,425] {standard_task_runner.py:97} ERROR - Failed to execute job 193 for task fetch_exchange_rates_task (name 'PostgresOperator' is not defined; 9272)
[2023-07-25 20:38:41,468] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-25 20:38:41,586] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-26 05:05:57,569] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T15:50:00+00:00 [queued]>
[2023-07-26 05:05:57,642] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T15:50:00+00:00 [queued]>
[2023-07-26 05:05:57,653] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 05:05:57,655] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-26 05:05:57,656] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 05:05:57,835] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): fetch_exchange_rates_task> on 2023-07-25 15:50:00+00:00
[2023-07-26 05:05:57,867] {standard_task_runner.py:52} INFO - Started process 1378 to run task
[2023-07-26 05:05:57,909] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fetch_exchange_rates_dag', 'fetch_exchange_rates_task', 'scheduled__2023-07-25T15:50:00+00:00', '--job-id', '339', '--raw', '--subdir', 'DAGS_FOLDER/my_calc_rates.py', '--cfg-path', '/tmp/tmpmoly9wyu', '--error-file', '/tmp/tmp5r33zjwq']
[2023-07-26 05:05:57,929] {standard_task_runner.py:80} INFO - Job 339: Subtask fetch_exchange_rates_task
[2023-07-26 05:05:58,678] {task_command.py:371} INFO - Running <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T15:50:00+00:00 [running]> on host acb6bca32630
[2023-07-26 05:05:59,004] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=marina_z
AIRFLOW_CTX_DAG_ID=fetch_exchange_rates_dag
AIRFLOW_CTX_TASK_ID=fetch_exchange_rates_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-25T15:50:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-25T15:50:00+00:00
[2023-07-26 05:05:59,443] {logging_mixin.py:115} INFO - Save a new file exchange_latest_BTC.csv
[2023-07-26 05:05:59,452] {logging_mixin.py:115} INFO - Create a new table exchange_latest_BTC
[2023-07-26 05:05:59,456] {logging_mixin.py:115} INFO - Insert into table exchange_latest_BTC
[2023-07-26 05:06:00,041] {logging_mixin.py:115} INFO - Save a new file exchange_latest_EUR.csv
[2023-07-26 05:06:00,042] {logging_mixin.py:115} INFO - Create a new table exchange_latest_EUR
[2023-07-26 05:06:00,058] {logging_mixin.py:115} INFO - Insert into table exchange_latest_EUR
[2023-07-26 05:06:00,564] {logging_mixin.py:115} INFO - Save a new file exchange_latest_GBR.csv
[2023-07-26 05:06:00,571] {logging_mixin.py:115} INFO - Create a new table exchange_latest_GBR
[2023-07-26 05:06:00,591] {logging_mixin.py:115} INFO - Insert into table exchange_latest_GBR
[2023-07-26 05:06:00,615] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_calc_rates.py", line 99, in fetch_exchange_rates
    cur.execute(copy_query)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type numeric: "2023-07-26"
CONTEXT:  COPY exchange_rates_gbr, line 3, column exchange_rate: "2023-07-26"

[2023-07-26 05:06:00,721] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=fetch_exchange_rates_dag, task_id=fetch_exchange_rates_task, execution_date=20230725T155000, start_date=20230726T050557, end_date=20230726T050600
[2023-07-26 05:06:00,864] {standard_task_runner.py:97} ERROR - Failed to execute job 339 for task fetch_exchange_rates_task (invalid input syntax for type numeric: "2023-07-26"
CONTEXT:  COPY exchange_rates_gbr, line 3, column exchange_rate: "2023-07-26"
; 1378)
[2023-07-26 05:06:00,967] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-26 05:06:01,153] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
