[2023-07-26 03:54:04,340] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.create_total_exchange_rates_table manual__2023-07-26T03:53:59.319594+00:00 [queued]>
[2023-07-26 03:54:04,352] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.create_total_exchange_rates_table manual__2023-07-26T03:53:59.319594+00:00 [queued]>
[2023-07-26 03:54:04,352] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 03:54:04,353] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-26 03:54:04,354] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 03:54:04,367] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): create_total_exchange_rates_table> on 2023-07-26 03:53:59.319594+00:00
[2023-07-26 03:54:04,373] {standard_task_runner.py:52} INFO - Started process 5735 to run task
[2023-07-26 03:54:04,375] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fetch_exchange_rates_dag', 'create_total_exchange_rates_table', 'manual__2023-07-26T03:53:59.319594+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/my_calc_rates.py', '--cfg-path', '/tmp/tmp5w9ybas0', '--error-file', '/tmp/tmp3fc4svve']
[2023-07-26 03:54:04,377] {standard_task_runner.py:80} INFO - Job 23: Subtask create_total_exchange_rates_table
[2023-07-26 03:54:04,442] {task_command.py:371} INFO - Running <TaskInstance: fetch_exchange_rates_dag.create_total_exchange_rates_table manual__2023-07-26T03:53:59.319594+00:00 [running]> on host 6e11a261c833
[2023-07-26 03:54:04,511] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=marina_z
AIRFLOW_CTX_DAG_ID=fetch_exchange_rates_dag
AIRFLOW_CTX_TASK_ID=create_total_exchange_rates_table
AIRFLOW_CTX_EXECUTION_DATE=2023-07-26T03:53:59.319594+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-26T03:53:59.319594+00:00
[2023-07-26 03:54:04,526] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_calc_rates.py", line 121, in create_total_exchange_rates_table
    cur.execute(save_csv)
psycopg2.errors.InvalidName: relative path not allowed for COPY to file

[2023-07-26 03:54:04,539] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=fetch_exchange_rates_dag, task_id=create_total_exchange_rates_table, execution_date=20230726T035359, start_date=20230726T035404, end_date=20230726T035404
[2023-07-26 03:54:04,550] {standard_task_runner.py:97} ERROR - Failed to execute job 23 for task create_total_exchange_rates_table (relative path not allowed for COPY to file
; 5735)
[2023-07-26 03:54:04,588] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-26 03:54:04,619] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
